
package javatest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "emailinterface", targetNamespace = "http://javatest/", wsdlLocation = "http://localhost:666/Webservice?wsdl")
public class Emailinterface_Service
    extends Service
{

    private final static URL EMAILINTERFACE_WSDL_LOCATION;
    private final static WebServiceException EMAILINTERFACE_EXCEPTION;
    private final static QName EMAILINTERFACE_QNAME = new QName("http://javatest/", "emailinterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:666/Webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMAILINTERFACE_WSDL_LOCATION = url;
        EMAILINTERFACE_EXCEPTION = e;
    }

    public Emailinterface_Service() {
        super(__getWsdlLocation(), EMAILINTERFACE_QNAME);
    }

    public Emailinterface_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMAILINTERFACE_QNAME, features);
    }

    public Emailinterface_Service(URL wsdlLocation) {
        super(wsdlLocation, EMAILINTERFACE_QNAME);
    }

    public Emailinterface_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMAILINTERFACE_QNAME, features);
    }

    public Emailinterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Emailinterface_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Emailinterface
     */
    @WebEndpoint(name = "javatestPort")
    public Emailinterface getJavatestPort() {
        return super.getPort(new QName("http://javatest/", "javatestPort"), Emailinterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Emailinterface
     */
    @WebEndpoint(name = "javatestPort")
    public Emailinterface getJavatestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://javatest/", "javatestPort"), Emailinterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMAILINTERFACE_EXCEPTION!= null) {
            throw EMAILINTERFACE_EXCEPTION;
        }
        return EMAILINTERFACE_WSDL_LOCATION;
    }

}
