
package javatest;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "emailinterface", targetNamespace = "http://javatest/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Emailinterface {


    /**
     * 
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkEmail", targetNamespace = "http://javatest/", className = "javatest.CheckEmail")
    @ResponseWrapper(localName = "checkEmailResponse", targetNamespace = "http://javatest/", className = "javatest.CheckEmailResponse")
    public boolean checkEmail(
        @WebParam(name = "url", targetNamespace = "")
        String url);

    /**
     * 
     * @param payload
     * @param url
     */
    @WebMethod(operationName = "SendEmail")
    @RequestWrapper(localName = "SendEmail", targetNamespace = "http://javatest/", className = "javatest.SendEmail")
    @ResponseWrapper(localName = "SendEmailResponse", targetNamespace = "http://javatest/", className = "javatest.SendEmailResponse")
    public void sendEmail(
        @WebParam(name = "url", targetNamespace = "")
        List<String> url,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

}
